import { useSession } from "next-auth/react";
import Head from "next/head";
import { useState } from "react";
import {
  Button,
  Container,
  Form,
  FormControl,
  FormGroup,
  FormLabel,
} from "react-bootstrap";
import { MAIN_TITLE } from "~/Config";
import { api } from "~/utils/api";

export default function Home() {
  // const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>{MAIN_TITLE}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <div className="mt-5">
            <UsernameForm />
          </div>
        </Container>
      </main>
    </>
  );
}

function UsernameForm() {
  const { data: sessionData } = useSession();
  const userUpdate = api.user.updateName.useMutation();
  const [name, setName] = useState("");

  const saveUsername = async () => {
    await userUpdate.mutateAsync({
      name,
    });
  };

  return (
    <div>
      {sessionData && !sessionData.user.name ? (
        <>
          <h2 className="text-center">Gib deinen Namen ein:</h2>
          <Form onSubmit={(e) => e.preventDefault()}>
            <FormGroup className="mb-3">
              <FormLabel htmlFor="name">Vor- & Nachname</FormLabel>
              <FormControl
                type="text"
                name="name"
                id="name"
                placeholder="Max Muster"
                value={name}
                onChange={(e) => setName(e.target.value)}
              />
            </FormGroup>
            <Button onClick={saveUsername}>Speichern</Button>
          </Form>
        </>
      ) : (
        <Container>
          <h1>{sessionData && <span>Hallo {sessionData.user.name}</span>}</h1>
          <LatestWritings />
          <LatestTests />
        </Container>
      )}
    </div>
  );
}

function LatestWritings() {
  const { data: sessionData } = useSession();
  if (sessionData)
    return (
      <Container className="mt-2">
        <h2>Aktuelle Texte</h2>
      </Container>
    );
}

function LatestTests() {
  const { data: sessionData } = useSession();
  if (sessionData)
    return (
      <Container className="mt-2">
        <h2>Aktuelle Tests</h2>
      </Container>
    );
}
